<a href="https://colab.research.google.com/github/PraveenChigurla/GrowTech-Tasks/blob/main/Pandas_data_from_external_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import requests
import json
from pandas import json_normalize

In [ ]:
response=requests.get("https://www.risingsigma.com/zippy-v2/json.php?shop=497b2f-97", allow_redirects=True)
print(response.headers.get('content-type'))
content=response.content
content

text/html; charset=UTF-8

b'{"border_width":"1px","but_width":"1px","icon":"1","heading":"DELIVERY OPTIONS","box_width":"220","box_style":"solid","box_color":"#afafaf","box_rad":"0","but_text":"Check","but_style":"solid","but_color":"#afafaf","but_rad":"0","succ_color":"#008000","fail_color":"#ff0000","placeholder_text":"Enter your zipcode","back_color":"#89216b","txt_color":"#ffffff","tooltip_text":"Please enter a zipcode below!","tooltip_back_color":"#ff0000","tooltip_txt_color":"#ffffff","wpos":"3","btn_selector":null,"cd_btn_selector":null,"pos_selector":null,"layout":"0","change_btn_text":"CHANGE","display_rule":"any","disp_rule_1":"1","disp_rule_2":"1","disp_rule_3":"1","rule_value_1":null,"rule_value_2":null,"rule_value_3":null,"cpos":"0","cdpos":"0","return_yes_msg":null,"return_no_msg":null,"output_heading":"Deliver to","heading_color":"#000000","heading_size":"14","cart_checkout_disabled":"0","cart_drawer_checkout_disabled":"0","indian_pin_check":"0","auto_submit_form":"0","popup_check_compulsory":"0","popup_restrict_store_entry":"0","watermark":"1","zipcode_cookie":"1","master_value":"1"}'

In [ ]:
type(response)

requests.models.Response

In [ ]:
data = json.loads(content) ## parse a JSON string and convert it into a Python Dictionary.
data

{'border_width': '1px',
 'but_width': '1px',
 'icon': '1',
 'heading': 'DELIVERY OPTIONS',
 'box_width': '220',
 'box_style': 'solid',
 'box_color': '#afafaf',
 'box_rad': '0',
 'but_text': 'Check',
 'but_style': 'solid',
 'but_color': '#afafaf',
 'but_rad': '0',
 'succ_color': '#008000',
 'fail_color': '#ff0000',
 'placeholder_text': 'Enter your zipcode',
 'back_color': '#89216b',
 'txt_color': '#ffffff',
 'tooltip_text': 'Please enter a zipcode below!',
 'tooltip_back_color': '#ff0000',
 'tooltip_txt_color': '#ffffff',
 'wpos': '3',
 'btn_selector': None,
 'cd_btn_selector': None,
 'pos_selector': None,
 'layout': '0',
 'change_btn_text': 'CHANGE',
 'display_rule': 'any',
 'disp_rule_1': '1',
 'disp_rule_2': '1',
 'disp_rule_3': '1',
 'rule_value_1': None,
 'rule_value_2': None,
 'rule_value_3': None,
 'cpos': '0',
 'cdpos': '0',
 'return_yes_msg': None,
 'return_no_msg': None,
 'output_heading': 'Deliver to',
 'heading_color': '#000000',
 'heading_size': '14',
 'cart_checkout_disabled': '0',
 'cart_drawer_checkout_disabled': '0',
 'indian_pin_check': '0',
 'auto_submit_form': '0',
 'popup_check_compulsory': '0',
 'popup_restrict_store_entry': '0',
 'watermark': '1',
 'zipcode_cookie': '1',
 'master_value': '1'}

In [ ]:
type(data)

dict

In [ ]:
data = json_normalize(data)# convert dictionary to dataframe
data

,border_width,but_width,icon,heading,box_width,box_style,box_color,box_rad,but_text,but_style,...,heading_size,cart_checkout_disabled,cart_drawer_checkout_disabled,indian_pin_check,auto_submit_form,popup_check_compulsory,popup_restrict_store_entry,watermark,zipcode_cookie,master_value
0,1px,1px,1,DELIVERY OPTIONS,220,solid,#afafaf,0,Check,solid,...,14,0,0,0,0,0,0,1,1,1

In [ ]:
type(data)

pandas.core.frame.DataFrame

In [ ]:
index = pd.DataFrame.from_dict(data['tooltip_text'])
index

                    tooltip_text
0  Please enter a zipcode below!

In [ ]:
index2 = pd.DataFrame.from_dict(data[''])