<a href="https://colab.research.google.com/github/PraveenChigurla/GrowTech-Tasks/blob/main/Task_2_Housing_Pandas_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Assignment on Housing Dataset



Make sure to load the dataset before starting:
```python
import pandas as pd

df = pd.read_csv("Housing.csv")
df.head()
```

In [77]:
import pandas as pd

df = pd.read_csv("Housing.csv")
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

### 1. Display the first 10 rows of the dataset.

In [78]:
df.head(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
9,9800000,5750,3,2,4,yes,yes,no,no,yes,1,yes,unfurnished

### 2. Show the shape of the dataset.

In [79]:
df.shape

(545, 13)

### 3. List all column names in the dataset.

In [80]:
df.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

### 4. Check for missing values in each column.

In [81]:
df[:].isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

### 5. Display the summary statistics for numerical columns.

In [82]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

### 6. How many unique values are there in the 'furnishingstatus' column?

In [83]:
df['furnishingstatus'].unique()

array(['furnished', 'semi-furnished', 'unfurnished'], dtype=object)

### 7. What is the average price of the houses?

In [84]:
df['price'].mean()

np.float64(4766729.247706422)

### 8. Find the median area of the houses.

In [85]:
df['area'].median()

4600.0

### 9. Count how many houses have 4 or more bedrooms.

In [86]:
df[df['bedrooms']>=4]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,2870000,5400,4,1,2,yes,no,no,no,no,0,no,unfurnished
488,2852500,5200,4,1,3,yes,no,no,no,no,0,no,unfurnished
523,2380000,2787,4,2,2,yes,no,no,no,no,0,no,furnished
534,2100000,3000,4,1,2,yes,no,no,no,no,0,no,unfurnished
536,1960000,3420,5,1,2,no,no,no,no,no,0,no,unfurnished

In [87]:
len(df[df['bedrooms']>=4])

107

### 10. Show the number of houses with parking space for more than 1 car.

In [88]:
df[df['parking']>1]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
448,3150000,4095,2,1,1,yes,no,no,no,no,2,no,semi-furnished
452,3150000,9000,3,1,2,yes,no,no,no,no,2,no,semi-furnished
467,3010000,3240,3,1,2,yes,no,no,no,no,2,no,semi-furnished
472,3010000,3630,4,1,2,yes,no,no,no,no,3,no,semi-furnished
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished

In [89]:
len(df[df['parking']>1])

120

### 11. Display the houses with both guestroom and basement.

In [90]:
df[(df['guestroom']=='yes') & (df['basement']=='yes')]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
11,9681000,6000,4,3,2,yes,yes,yes,yes,no,2,no,semi-furnished
16,9100000,6600,4,2,2,yes,yes,yes,no,yes,1,yes,unfurnished
21,8680000,7155,3,2,1,yes,yes,yes,no,yes,2,no,unfurnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,3640000,5960,3,1,2,yes,yes,yes,no,no,0,no,unfurnished
415,3395000,4785,3,1,2,yes,yes,yes,no,yes,1,no,furnished
432,3290000,6060,3,1,1,yes,yes,yes,no,no,0,no,furnished
446,3150000,3986,2,2,1,no,yes,yes,no,no,1,no,unfurnished
463,3080000,3090,2,1,1,yes,yes,yes,no,no,0,no,unfurnished

### 12. How many houses are there with air conditioning but no hot water heating?

In [91]:
df[(df['airconditioning']=='yes') & (df['hotwaterheating']=='no')]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,3115000,3000,3,1,1,no,no,no,no,yes,0,no,unfurnished
461,3080000,4960,2,1,1,yes,no,yes,no,yes,0,no,unfurnished
504,2653000,3185,2,1,1,yes,no,no,no,yes,0,no,unfurnished
505,2653000,4000,3,1,2,yes,no,no,no,yes,0,no,unfurnished
531,2233000,5300,3,1,1,no,no,no,no,yes,0,yes,unfurnished

In [92]:
len(df[(df['airconditioning']=='yes') & (df['hotwaterheating']=='no')])

171

### 13. Create a new column 'price_per_sqft' (price divided by area).

In [93]:
df['price_per_sqft']=df['price']/df['area']
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,1792.452830
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,1367.187500
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,1229.919679
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,1628.666667
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,1537.735849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished,606.666667
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished,736.312500
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished,483.425414
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished,601.374570
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished,454.545455

### 14. What is the average price per square foot?

In [94]:
df['price_per_sqft'].mean()

np.float64(993.3269783651732)

In [95]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,1792.452830
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,1367.187500
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,1229.919679
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,1628.666667
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,1537.735849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished,606.666667
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished,736.312500
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished,483.425414
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished,601.374570
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished,454.545455

### 15. Group the data by 'furnishingstatus' and find the average price for each group.

In [96]:
x=df.groupby('furnishingstatus')
x['price'].mean()

furnishingstatus
furnished         5.495696e+06
semi-furnished    4.907524e+06
unfurnished       4.013831e+06
Name: price, dtype: float64

### 16. Find the number of houses located on the main road.

In [97]:
df[df['mainroad']=='yes']

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,1792.452830
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,1367.187500
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,1229.919679
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,1628.666667
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,1537.735849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,1890000,1700,3,1,2,yes,no,no,no,no,0,no,unfurnished,1111.764706
538,1890000,3649,2,1,1,yes,no,no,no,no,0,no,unfurnished,517.950123
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished,606.666667
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished,483.425414
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished,454.545455

In [98]:
len(df[df['mainroad']=='yes'])

468

### 17. Show the distribution of the 'stories' column using value counts.

In [99]:
df['stories'].value_counts()

stories
2    238
1    227
4     41
3     39
Name: count, dtype: int64

### 18. How many houses have 2 bathrooms and are located in a preferred area?

In [100]:
df[(df['bathrooms']==2) & (df['prefarea']=='yes')]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,1792.452830
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,1229.919679
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,1628.666667
9,9800000,5750,3,2,4,yes,yes,no,no,yes,1,yes,unfurnished,1704.347826
12,9310000,6550,4,2,2,yes,no,no,no,yes,1,yes,semi-furnished,1421.374046
14,9240000,7800,3,2,2,yes,no,no,no,no,0,yes,semi-furnished,1184.615385
16,9100000,6600,4,2,2,yes,yes,yes,no,yes,1,yes,unfurnished,1378.787879
19,8855000,6420,3,2,2,yes,no,no,no,yes,1,yes,semi-furnished,1379.283489
25,8540000,6540,4,2,2,yes,yes,yes,no,yes,2,yes,furnished,1305.810398
26,8463000,6000,3,2,4,yes,yes,yes,no,yes,0,yes,semi-furnished,1410.500000
29,8400000,5500,4,2,2,yes,no,yes,no,yes,1,yes,semi-furnished,1527.272727
32,8295000,4880,4,2,2,yes,no,no,no,yes,1,yes,furnished,1699.795082
36,8043000,7482,3,2,3,yes,no,no,yes,no,1,yes,furnished,1074.979952
41,7840000,6360,3,2,4,yes,no,no,no,yes,0,yes,furnished,1232.704403
49,7420000,7440,3,2,1,yes,yes,yes,no,yes,0,yes,semi-furnished,997.311828
50,7420000,7440,3,2,4,yes,no,no,no,no,1,yes,unfurnished,997.311828
57,7245000,9000,4,2,4,yes,yes,no,no,yes,1,yes,furnished,805.000000
63,7035000,6360,4,2,3,yes,no,no,no,yes,2,yes,furnished,1106.132075
69,6790000,12090,4,2,2,yes,no,no,no,no,2,yes,furnished,561.621175
70,6790000,4000,3,2,2,yes,no,yes,no,yes,0,yes,semi-furnished,1697.500000
73,6685000,6600,2,2,4,yes,no,yes,no,no,0,yes,furnished,1012.878788
76,6650000,6420,3,2,3,yes,no,no,no,yes,0,yes,furnished,1035.825545
77,6650000,6500,3,2,3,yes,no,no,no,yes,0,yes,furnished,1023.076923
82,6615000,10500,3,2,1,yes,no,yes,no,yes,1,yes,furnished,630.000000
98,6293000,6600,3,2,3,yes,no,no,no,yes,0,yes,unfurnished,953.484848
100,6230000,6600,3,2,1,yes,no,yes,no,yes,0,yes,unfurnished,943.939394
104,6195000,5500,3,2,1,yes,yes,yes,no,no,2,yes,furnished,1126.363636
106,6160000,5450,4,2,1,yes,no,yes,no,yes,0,yes,semi-furnished,1130.275229
116,6020000,6900,3,2,1,yes,yes,yes,no,no,0,yes,unfurnished,872.463768
122,5950000,6254,4,2,1,yes,no,yes,no,no,1,yes,semi-furnished,951.391110
141,5652500,6660,4,2,2,yes,yes,yes,no,no,1,yes,semi-furnished,848.723724
149,5600000,6600,4,2,1,yes,no,yes,no,no,0,yes,semi-furnished,848.484848
155,5530000,6100,3,2,1,yes,no,yes,no,no,2,yes,furnished,906.557377
162,5460000,6600,4,2,2,yes,yes,yes,no,no,0,yes,semi-furnished,827.272727
164,5390000,6710,3,2,2,yes,yes,yes,no,no,1,yes,furnished,803.278689
173,5250000,5300,4,2,1,yes,no,no,no,yes,0,yes,unfurnished,990.566038
249,4543000,4990,4,2,2,yes,yes,yes,no,no,0,yes,furnished,910.420842
337,3920000,2145,4,2,1,yes,no,yes,no,no,0,yes,unfurnished,1827.505828
377,3640000,2850,3,2,2,no,no,yes,no,no,0,yes,unfurnished,1277.192982
413,3430000,1950,3,2,2,yes,no,yes,no,no,0,yes,unfurnished,1758.974359

In [101]:
len(df[(df['bathrooms']==2) & (df['prefarea']=='yes')])

40

### 19. What is the maximum and minimum area of a house?

In [102]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking,price_per_sqft
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578,993.326978
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586,346.537025
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000,270.395550
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000,745.370370
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000,952.380952
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000,1184.615385
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000,2640.000000

In [103]:
df['area'].min()

1650

In [104]:
df['area'].max()

16200

### 20. Sort the dataset by price in descending order.

In [105]:
df.sort_values('price',ascending=False)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,1792.452830
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,1229.919679
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,1367.187500
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,1628.666667
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,1537.735849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished,606.666667
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished,736.312500
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished,601.374570
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished,483.425414
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished,454.545455

### 24. Replace 'yes' and 'no' with True and False across the dataset.

In [106]:
import numpy as np
df2=df
df2[:]=np.where(df.values=='yes',True,np.where(df.values == 'no', False, df.values))

df2

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft
0,13300000,7420,4,2,3,True,False,False,False,True,2,True,furnished,1792.452830
1,12250000,8960,4,4,4,True,False,False,False,True,3,False,furnished,1367.187500
2,12250000,9960,3,2,2,True,False,True,False,False,2,True,semi-furnished,1229.919679
3,12215000,7500,4,2,2,True,False,True,False,True,3,True,furnished,1628.666667
4,11410000,7420,4,1,2,True,True,True,False,True,2,False,furnished,1537.735849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,True,False,True,False,False,2,False,unfurnished,606.666667
541,1767150,2400,3,1,1,False,False,False,False,False,0,False,semi-furnished,736.312500
542,1750000,3620,2,1,1,True,False,False,False,False,0,False,unfurnished,483.425414
543,1750000,2910,3,1,1,False,False,False,False,False,0,False,furnished,601.374570
544,1750000,3850,3,1,2,True,False,False,False,False,0,False,unfurnished,454.545455

In [107]:
df.replace(['yes', 'no'],['True','False'])

/tmp/ipykernel_3998/538738943.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(['yes', 'no'],['True','False'])

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft
0,13300000,7420,4,2,3,True,False,False,False,True,2,True,furnished,1792.452830
1,12250000,8960,4,4,4,True,False,False,False,True,3,False,furnished,1367.187500
2,12250000,9960,3,2,2,True,False,True,False,False,2,True,semi-furnished,1229.919679
3,12215000,7500,4,2,2,True,False,True,False,True,3,True,furnished,1628.666667
4,11410000,7420,4,1,2,True,True,True,False,True,2,False,furnished,1537.735849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,True,False,True,False,False,2,False,unfurnished,606.666667
541,1767150,2400,3,1,1,False,False,False,False,False,0,False,semi-furnished,736.312500
542,1750000,3620,2,1,1,True,False,False,False,False,0,False,unfurnished,483.425414
543,1750000,2910,3,1,1,False,False,False,False,False,0,False,furnished,601.374570
544,1750000,3850,3,1,2,True,False,False,False,False,0,False,unfurnished,454.545455

### 25. Find out the average area of unfurnished houses.

In [108]:
df[df['furnishingstatus']=='unfurnished']

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft
7,10150000,16200,5,3,2,True,False,False,False,False,0,False,unfurnished,626.543210
9,9800000,5750,3,2,4,True,True,False,False,True,1,True,unfurnished,1704.347826
16,9100000,6600,4,2,2,True,True,True,False,True,1,True,unfurnished,1378.787879
21,8680000,7155,3,2,1,True,True,True,False,True,2,False,unfurnished,1213.137666
28,8400000,7950,5,2,2,True,False,True,True,False,2,False,unfurnished,1056.603774
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
538,1890000,3649,2,1,1,True,False,False,False,False,0,False,unfurnished,517.950123
539,1855000,2990,2,1,1,False,False,False,False,False,1,False,unfurnished,620.401338
540,1820000,3000,2,1,1,True,False,True,False,False,2,False,unfurnished,606.666667
542,1750000,3620,2,1,1,True,False,False,False,False,0,False,unfurnished,483.425414
544,1750000,3850,3,1,2,True,False,False,False,False,0,False,unfurnished,454.545455

In [109]:
df[df['furnishingstatus']=='unfurnished']['price']

7      10150000
9       9800000
16      9100000
21      8680000
28      8400000
         ...
538     1890000
539     1855000
540     1820000
542     1750000
544     1750000
Name: price, Length: 178, dtype: int64

In [110]:
(df[df['furnishingstatus']=='unfurnished']['price']).mean()

np.float64(4013831.4606741574)

### 26. Filter out houses with price above the average price.

In [111]:
df['price'].mean()

np.float64(4766729.247706422)

In [112]:
df[df['price']>df['price'].mean()]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft
0,13300000,7420,4,2,3,True,False,False,False,True,2,True,furnished,1792.452830
1,12250000,8960,4,4,4,True,False,False,False,True,3,False,furnished,1367.187500
2,12250000,9960,3,2,2,True,False,True,False,False,2,True,semi-furnished,1229.919679
3,12215000,7500,4,2,2,True,False,True,False,True,3,True,furnished,1628.666667
4,11410000,7420,4,1,2,True,True,True,False,True,2,False,furnished,1537.735849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,4830000,6862,3,1,2,True,False,False,False,True,2,True,furnished,703.876421
218,4830000,4815,2,1,1,True,False,False,False,True,0,True,semi-furnished,1003.115265
219,4795000,7000,3,1,2,True,False,True,False,False,0,False,unfurnished,685.000000
220,4795000,8100,4,1,4,True,False,True,False,True,2,False,semi-furnished,591.975309
221,4767000,3420,4,2,2,True,False,False,False,False,0,False,semi-furnished,1393.859649

### 27. Identify the house with the highest price and display all its features.

In [113]:
df3=df
df3.sort_values('price',ascending=False)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft
0,13300000,7420,4,2,3,True,False,False,False,True,2,True,furnished,1792.452830
2,12250000,9960,3,2,2,True,False,True,False,False,2,True,semi-furnished,1229.919679
1,12250000,8960,4,4,4,True,False,False,False,True,3,False,furnished,1367.187500
3,12215000,7500,4,2,2,True,False,True,False,True,3,True,furnished,1628.666667
4,11410000,7420,4,1,2,True,True,True,False,True,2,False,furnished,1537.735849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,True,False,True,False,False,2,False,unfurnished,606.666667
541,1767150,2400,3,1,1,False,False,False,False,False,0,False,semi-furnished,736.312500
543,1750000,2910,3,1,1,False,False,False,False,False,0,False,furnished,601.374570
542,1750000,3620,2,1,1,True,False,False,False,False,0,False,unfurnished,483.425414
544,1750000,3850,3,1,2,True,False,False,False,False,0,False,unfurnished,454.545455

In [114]:
df3.iloc[0]

price                 13300000
area                      7420
bedrooms                     4
bathrooms                    2
stories                      3
mainroad                  True
guestroom                False
basement                 False
hotwaterheating          False
airconditioning           True
parking                      2
prefarea                  True
furnishingstatus     furnished
price_per_sqft      1792.45283
Name: 0, dtype: object

### 28. How many houses are both furnished and have at least 3 bathrooms?

In [115]:
df[(df['furnishingstatus']=='furnished') & (df['bathrooms']>=3)]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft
1,12250000,8960,4,4,4,True,False,False,False,True,3,False,furnished,1367.187500
89,6440000,8580,5,3,2,True,False,False,False,False,2,False,furnished,750.582751

In [116]:
len(df[(df['furnishingstatus']=='furnished') & (df['bathrooms']>=3)])

2

### 29. Create a pivot table showing average price by 'furnishingstatus' and 'airconditioning'.

In [117]:
pd.pivot_table(
    df,
    values='price',
    index='furnishingstatus',
    columns='airconditioning',
    aggfunc='mean'
    )

airconditioning          False         True
furnishingstatus
furnished         4.469500e+06  6.786717e+06
semi-furnished    4.557951e+06  5.778769e+06
unfurnished       3.583342e+06  5.286167e+06

### 30. Save the modified dataset with a new column into a new CSV file named 'Modified_Housing.csv'.

In [118]:
df5=df
df5

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft
0,13300000,7420,4,2,3,True,False,False,False,True,2,True,furnished,1792.452830
1,12250000,8960,4,4,4,True,False,False,False,True,3,False,furnished,1367.187500
2,12250000,9960,3,2,2,True,False,True,False,False,2,True,semi-furnished,1229.919679
3,12215000,7500,4,2,2,True,False,True,False,True,3,True,furnished,1628.666667
4,11410000,7420,4,1,2,True,True,True,False,True,2,False,furnished,1537.735849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,True,False,True,False,False,2,False,unfurnished,606.666667
541,1767150,2400,3,1,1,False,False,False,False,False,0,False,semi-furnished,736.312500
542,1750000,3620,2,1,1,True,False,False,False,False,0,False,unfurnished,483.425414
543,1750000,2910,3,1,1,False,False,False,False,False,0,False,furnished,601.374570
544,1750000,3850,3,1,2,True,False,False,False,False,0,False,unfurnished,454.545455

In [119]:
df5['balcony']=np.random.choice(['yes','no'],size=len(df5))
df5.to_csv('Modified_Housing.csv')

In [120]:
df5[df5['balcony']=='yes']

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft,balcony
2,12250000,9960,3,2,2,True,False,True,False,False,2,True,semi-furnished,1229.919679,yes
3,12215000,7500,4,2,2,True,False,True,False,True,3,True,furnished,1628.666667,yes
4,11410000,7420,4,1,2,True,True,True,False,True,2,False,furnished,1537.735849,yes
5,10850000,7500,3,3,1,True,False,True,False,True,2,True,semi-furnished,1446.666667,yes
6,10150000,8580,4,3,4,True,False,False,False,True,2,True,semi-furnished,1182.983683,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
533,2100000,2400,3,1,2,True,False,False,False,False,0,False,unfurnished,875.000000,yes
536,1960000,3420,5,1,2,False,False,False,False,False,0,False,unfurnished,573.099415,yes
540,1820000,3000,2,1,1,True,False,True,False,False,2,False,unfurnished,606.666667,yes
541,1767150,2400,3,1,1,False,False,False,False,False,0,False,semi-furnished,736.312500,yes
544,1750000,3850,3,1,2,True,False,False,False,False,0,False,unfurnished,454.545455,yes

In [121]:
df5[df5['balcony']=='no']

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft,balcony
0,13300000,7420,4,2,3,True,False,False,False,True,2,True,furnished,1792.452830,no
1,12250000,8960,4,4,4,True,False,False,False,True,3,False,furnished,1367.187500,no
7,10150000,16200,5,3,2,True,False,False,False,False,0,False,unfurnished,626.543210,no
8,9870000,8100,4,1,2,True,True,True,False,True,2,True,furnished,1218.518519,no
10,9800000,13200,3,1,2,True,False,True,False,True,2,True,furnished,742.424242,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,1890000,1700,3,1,2,True,False,False,False,False,0,False,unfurnished,1111.764706,no
538,1890000,3649,2,1,1,True,False,False,False,False,0,False,unfurnished,517.950123,no
539,1855000,2990,2,1,1,False,False,False,False,False,1,False,unfurnished,620.401338,no
542,1750000,3620,2,1,1,True,False,False,False,False,0,False,unfurnished,483.425414,no
543,1750000,2910,3,1,1,False,False,False,False,False,0,False,furnished,601.374570,no

### 31.Find the top 5 most expensive houses for each furnishing status.

In [122]:
x=df.groupby('furnishingstatus')['price'].nlargest(5)
x

furnishingstatus
furnished         0     13300000
                  1     12250000
                  3     12215000
                  4     11410000
                  8      9870000
semi-furnished    2     12250000
                  5     10850000
                  6     10150000
                  11     9681000
                  12     9310000
unfurnished       7     10150000
                  9      9800000
                  16     9100000
                  21     8680000
                  28     8400000
Name: price, dtype: int64

### 32 Create a new column 'luxury' where a house is considered luxury if it has price > 1.5× mean and is in a preferred area.

In [123]:
df4=df
df4['luxury']=(df4['price'])> (1.5 * df4['price'].mean())
df4

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft,balcony,luxury
0,13300000,7420,4,2,3,True,False,False,False,True,2,True,furnished,1792.452830,no,True
1,12250000,8960,4,4,4,True,False,False,False,True,3,False,furnished,1367.187500,no,True
2,12250000,9960,3,2,2,True,False,True,False,False,2,True,semi-furnished,1229.919679,yes,True
3,12215000,7500,4,2,2,True,False,True,False,True,3,True,furnished,1628.666667,yes,True
4,11410000,7420,4,1,2,True,True,True,False,True,2,False,furnished,1537.735849,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,True,False,True,False,False,2,False,unfurnished,606.666667,yes,False
541,1767150,2400,3,1,1,False,False,False,False,False,0,False,semi-furnished,736.312500,yes,False
542,1750000,3620,2,1,1,True,False,False,False,False,0,False,unfurnished,483.425414,no,False
543,1750000,2910,3,1,1,False,False,False,False,False,0,False,furnished,601.374570,no,False
544,1750000,3850,3,1,2,True,False,False,False,False,0,False,unfurnished,454.545455,yes,False

In [124]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft,balcony,luxury
0,13300000,7420,4,2,3,True,False,False,False,True,2,True,furnished,1792.452830,no,True
1,12250000,8960,4,4,4,True,False,False,False,True,3,False,furnished,1367.187500,no,True
2,12250000,9960,3,2,2,True,False,True,False,False,2,True,semi-furnished,1229.919679,yes,True
3,12215000,7500,4,2,2,True,False,True,False,True,3,True,furnished,1628.666667,yes,True
4,11410000,7420,4,1,2,True,True,True,False,True,2,False,furnished,1537.735849,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,True,False,True,False,False,2,False,unfurnished,606.666667,yes,False
541,1767150,2400,3,1,1,False,False,False,False,False,0,False,semi-furnished,736.312500,yes,False
542,1750000,3620,2,1,1,True,False,False,False,False,0,False,unfurnished,483.425414,no,False
543,1750000,2910,3,1,1,False,False,False,False,False,0,False,furnished,601.374570,no,False
544,1750000,3850,3,1,2,True,False,False,False,False,0,False,unfurnished,454.545455,yes,False

### For each number of stories, calculate the median price, and standard deviation of area.

In [125]:
df.groupby('stories').agg({'price':'median', 'area':'std'})

             price         area
stories
1        3850000.0  2275.977836
2        4308500.0  2122.466037
3        5873000.0  1977.331302
4        7350000.0  1197.437867

### Pivot the data to show average price with bedrooms as rows and stories as columns.

In [126]:
pd.pivot_table(
    df,
    values='price',
    index='bedrooms',
    columns='stories',
    aggfunc='mean'
)

stories              1             2             3             4
bedrooms
1         2.712500e+06           NaN           NaN           NaN
2         3.580165e+06  3.777550e+06           NaN  6.685000e+06
3         4.800441e+06  4.535290e+06  5.585548e+06  7.193458e+06
4         5.122250e+06  5.405292e+06  6.140000e+06  7.268333e+06
5         3.773000e+06  6.103125e+06  5.600000e+06           NaN
6                  NaN  4.791500e+06           NaN           NaN

In [127]:
pd.pivot_table(
    df,
    values='price',
    index='bedrooms',
    columns='stories',
    aggfunc='mean',
    fill_value=0
)

stories              1             2             3             4
bedrooms
1         2.712500e+06  0.000000e+00  0.000000e+00  0.000000e+00
2         3.580165e+06  3.777550e+06  0.000000e+00  6.685000e+06
3         4.800441e+06  4.535290e+06  5.585548e+06  7.193458e+06
4         5.122250e+06  5.405292e+06  6.140000e+06  7.268333e+06
5         3.773000e+06  6.103125e+06  5.600000e+06  0.000000e+00
6         0.000000e+00  4.791500e+06  0.000000e+00  0.000000e+00

In [128]:
df.pivot_table(
    values='price',
    index='bedrooms',
    columns='stories',
    aggfunc='mean'
)

stories              1             2             3             4
bedrooms
1         2.712500e+06           NaN           NaN           NaN
2         3.580165e+06  3.777550e+06           NaN  6.685000e+06
3         4.800441e+06  4.535290e+06  5.585548e+06  7.193458e+06
4         5.122250e+06  5.405292e+06  6.140000e+06  7.268333e+06
5         3.773000e+06  6.103125e+06  5.600000e+06           NaN
6                  NaN  4.791500e+06           NaN           NaN

### Using groupby, find the proportion of houses in each 'furnishingstatus' that have air conditioning.

In [129]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft,balcony,luxury
0,13300000,7420,4,2,3,True,False,False,False,True,2,True,furnished,1792.452830,no,True
1,12250000,8960,4,4,4,True,False,False,False,True,3,False,furnished,1367.187500,no,True
2,12250000,9960,3,2,2,True,False,True,False,False,2,True,semi-furnished,1229.919679,yes,True
3,12215000,7500,4,2,2,True,False,True,False,True,3,True,furnished,1628.666667,yes,True
4,11410000,7420,4,1,2,True,True,True,False,True,2,False,furnished,1537.735849,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,True,False,True,False,False,2,False,unfurnished,606.666667,yes,False
541,1767150,2400,3,1,1,False,False,False,False,False,0,False,semi-furnished,736.312500,yes,False
542,1750000,3620,2,1,1,True,False,False,False,False,0,False,unfurnished,483.425414,no,False
543,1750000,2910,3,1,1,False,False,False,False,False,0,False,furnished,601.374570,no,False
544,1750000,3850,3,1,2,True,False,False,False,False,0,False,unfurnished,454.545455,yes,False

### Group by 'furnishingstatus' and 'airconditioning' and calculate the average price and average area.

In [130]:
df.groupby(['furnishingstatus','airconditioning']).mean(['price','area'])

                                         price         area  bedrooms  \
furnishingstatus airconditioning
furnished        False            4.469500e+06  5157.448718  2.871795
                 True             6.786717e+06  6355.693548  3.306452
semi-furnished   False            4.557951e+06  4935.320988  2.962963
                 True             5.778769e+06  5742.107692  3.123077
unfurnished      False            3.583342e+06  4490.353383  2.796992
                 True             5.286167e+06  5349.666667  2.933333

                                  bathrooms   stories   parking  \
furnishingstatus airconditioning
furnished        False             1.269231  1.666667  0.717949
                 True              1.516129  2.290323  1.096774
semi-furnished   False             1.253086  1.685185  0.672840
                 True              1.430769  2.092308  0.892308
unfurnished      False             1.157895  1.548872  0.443609
                 True              1.288889  2.155556  0.622222

                                  price_per_sqft    luxury
furnishingstatus airconditioning
furnished        False                989.986634  0.025641
                 True                1117.967875  0.387097
semi-furnished   False               1017.119012  0.049383
                 True                1071.084297  0.200000
unfurnished      False                859.695513  0.037594
                 True                1024.377224  0.177778

### Calculate the average number of bedrooms per furnishing status, only for houses with area > 5000

In [131]:
df[df['area']>5000].groupby('furnishingstatus').mean('bedrooms')

,price,area,bedrooms,bathrooms,stories,parking,price_per_sqft,luxury
furnishingstatus,,,,,,,,
furnished,6.507146e+06,7486.360000,3.146667,1.480000,2.093333,1.213333,898.329850,0.293333
semi-furnished,5.778893e+06,7050.602041,3.132653,1.387755,1.846939,0.918367,854.239404,0.204082
unfurnished,5.386000e+06,6766.777778,3.031746,1.365079,2.079365,0.777778,823.488365,0.190476

### For each unique combination of bedrooms and bathrooms, compute the average price.

In [132]:
df.groupby(['bedrooms', 'bathrooms'])['price'].mean().reset_index()

    bedrooms  bathrooms         price
0          1          1  2.712500e+06
1          2          1  3.596852e+06
2          2          2  4.194750e+06
3          3          1  4.463484e+06
4          3          2  6.379569e+06
5          3          3  6.807500e+06
6          4          1  4.710583e+06
7          4          2  6.358990e+06
8          4          3  7.250250e+06
9          4          4  1.225000e+07
10         5          1  4.996250e+06
11         5          2  5.405750e+06
12         5          3  8.295000e+06
13         6          1  3.500000e+06
14         6          2  6.083000e+06

### Find the top 10% most expensive houses within each furnishingstatus category.

In [133]:
df.groupby('furnishingstatus').apply( lambda x: x[x['price'] >= x['price'].quantile(0.90)] )

/tmp/ipykernel_3998/2290538846.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('furnishingstatus').apply( lambda x: x[x['price'] >= x['price'].quantile(0.90)] )

                        price   area  bedrooms  bathrooms  stories mainroad  \
furnishingstatus
furnished        0   13300000   7420         4          2        3     True
                 1   12250000   8960         4          4        4     True
                 3   12215000   7500         4          2        2     True
                 4   11410000   7420         4          1        2     True
                 8    9870000   8100         4          1        2     True
                 10   9800000  13200         3          1        2     True
                 13   9240000   3500         4          2        2     True
                 17   8960000   8500         3          2        4     True
                 18   8890000   4600         3          2        2     True
                 22   8645000   8050         3          1        1     True
                 23   8645000   4560         3          2        2     True
                 24   8575000   8800         3          2        2     True
                 25   8540000   6540         4          2        2     True
                 32   8295000   4880         4          2        2     True
semi-furnished   2   12250000   9960         3          2        2     True
                 5   10850000   7500         3          3        1     True
                 6   10150000   8580         4          3        4     True
                 11   9681000   6000         4          3        2     True
                 12   9310000   6550         4          2        2     True
                 14   9240000   7800         3          2        2     True
                 15   9100000   6000         4          1        2     True
                 19   8855000   6420         3          2        2     True
                 20   8750000   4320         3          1        2     True
                 26   8463000   6000         3          2        4     True
                 27   8400000   8875         3          1        1     True
                 29   8400000   5500         4          2        2     True
                 31   8400000   7000         3          1        4     True
                 39   7910000   6000         4          2        4     True
                 43   7700000   6000         4          2        4     True
                 45   7560000   6000         3          2        3     True
                 49   7420000   7440         3          2        1     True
                 53   7350000   5150         3          2        4     True
                 54   7350000   6000         3          2        2     True
                 56   7343000  11440         4          1        2     True
                 58   7210000   7680         4          2        4     True
                 60   7140000   6000         3          2        2     True
                 61   7070000   8880         2          1        1     True
unfurnished      7   10150000  16200         5          3        2     True
                 9    9800000   5750         3          2        4     True
                 16   9100000   6600         4          2        2     True
                 21   8680000   7155         3          2        1     True
                 28   8400000   7950         5          2        2     True
                 30   8400000   7475         3          2        4     True
                 33   8190000   5960         3          3        2     True
                 38   7962500   6000         3          1        4     True
                 42   7700000   6480         3          2        4     True
                 48   7455000   4300         3          2        2     True
                 50   7420000   7440         3          2        4     True
                 51   7420000   6325         3          1        4     True
                 55   7350000   6000         3          1        2     True
                 67   6895000   7700         3          2        1     True
                 71   6755000   6000         4          2        4     True
                 72   6720000   5020         3          1        4     True
                 86   6510000   6670         3          1        3     True
                 88   6475000   7410         3          1        1     True

                    guestroom basement hotwaterheating airconditioning  \
furnishingstatus
furnished        0      False    False           False            True
                 1      False    False           False            True
                 3      False     True           False            True
                 4       True     True           False            True
                 8       True     True           False            True
                 10     False     True           False            True
                 13     False    False            True           False
                 17     False    False           False            True
                 18      True    False           False            True
                 22      True     True           False            True
                 23      True     True           False            True
                 24     False    False           False            True
                 25      True     True           False            True
                 32     False    False           False            True
semi-furnished   2      False     True           False           False
                 5      False     True           False            True
                 6      False    False           False            True
                 11      True     True            True           False
                 12     False    False           False            True
                 14     False    False           False           False
                 15     False     True           False           False
                 19     False    False           False            True
                 20     False     True            True           False
                 26      True     True           False            True
                 27     False    False           False           False
                 29     False     True           False            True
                 31     False    False           False            True
                 39     False    False           False            True
                 43     False    False           False           False
                 45     False    False           False            True
                 49      True     True           False            True
                 53     False    False           False            True
                 54      True    False           False            True
                 56     False     True           False           False
                 58      True    False           False            True
                 60      True    False           False           False
                 61     False    False           False            True
unfurnished      7      False    False           False           False
                 9       True    False           False            True
                 16      True     True           False            True
                 21      True     True           False            True
                 28     False     True            True           False
                 30     False    False           False            True
                 33      True     True           False           False
                 38      True    False           False            True
                 42     False    False           False            True
                 48     False     True           False           False
                 50     False    False           False           False
                 51     False    False           False            True
                 55     False    False           False            True
                 67     False    False           False           False
                 71     False    False           False            True
                 72     False    False           False            True
                 86     False     True           False           False
                 88      True     True           False            True

                     parking prefarea furnishingstatus  price_per_sqft  \
furnishingstatus
furnished        0         2     True        furnished     1792.452830
                 1         3    False        furnished     1367.187500
                 3         3     True        furnished     1628.666667
                 4         2    False        furnished     1537.735849
                 8         2     True        furnished     1218.518519
                 10        2     True        furnished      742.424242
                 13        2    False        furnished     2640.000000
                 17        2    False        furnished     1054.117647
                 18        2    False        furnished     1932.608696
                 22        1    False        furnished     1073.913043
                 23        1    False        furnished     1895.833333
                 24        2    False        furnished      974.431818
                 25        2     True        furnished     1305.810398
                 32        1     True        furnished     1699.795082
semi-furnished   2         2     True   semi-furnished     1229.919679
                 5         2     True   semi-furnished     1446.666667
                 6         2     True   semi-furnished     1182.983683
                 11        2    False   semi-furnished     1613.500000
                 12        1     True   semi-furnished     1421.374046
                 14        0     True   semi-furnished     1184.615385
                 15        2    False   semi-furnished     1516.666667
                 19        1     True   semi-furnished     1379.283489
                 20        2    False   semi-furnished     2025.462963
                 26        0     True   semi-furnished     1410.500000
                 27        1    False   semi-furnished      946.478873
                 29        1     True   semi-furnished     1527.272727
                 31        2    False   semi-furnished     1200.000000
                 39        1    False   semi-furnished     1318.333333
                 43        2    False   semi-furnished     1283.333333
                 45        0    False   semi-furnished     1260.000000
                 49        0     True   semi-furnished      997.311828
                 53        2    False   semi-furnished     1427.184466
                 54        1    False   semi-furnished     1225.000000
                 56        1     True   semi-furnished      641.870629
                 58        1    False   semi-furnished      938.802083
                 60        1    False   semi-furnished     1190.000000
                 61        1    False   semi-furnished      796.171171
unfurnished      7         0    False      unfurnished      626.543210
                 9         1     True      unfurnished     1704.347826
                 16        1     True      unfurnished     1378.787879
                 21        2    False      unfurnished     1213.137666
                 28        2    False      unfurnished     1056.603774
                 30        2    False      unfurnished     1123.745819
                 33        1    False      unfurnished     1374.161074
                 38        2    False      unfurnished     1327.083333
                 42        2    False      unfurnished     1188.271605
                 48        1    False      unfurnished     1733.720930
                 50        1     True      unfurnished      997.311828
                 51        1    False      unfurnished     1173.122530
                 55        1    False      unfurnished     1225.000000
                 67        2    False      unfurnished      895.454545
                 71        0    False      unfurnished     1125.833333
                 72        0     True      unfurnished     1338.645418
                 86        0     True      unfurnished      976.011994
                 88        2     True      unfurnished      873.819163

                    balcony  luxury
furnishingstatus
furnished        0       no    True
                 1       no    True
                 3      yes    True
                 4      yes    True
                 8       no    True
                 10      no    True
                 13     yes    True
                 17      no    True
                 18      no    True
                 22     yes    True
                 23      no    True
                 24      no    True
                 25     yes    True
                 32      no    True
semi-furnished   2      yes    True
                 5      yes    True
                 6      yes    True
                 11      no    True
                 12     yes    True
                 14     yes    True
                 15     yes    True
                 19      no    True
                 20      no    True
                 26     yes    True
                 27     yes    True
                 29      no    True
                 31     yes    True
                 39     yes    True
                 43     yes    True
                 45     yes    True
                 49      no    True
                 53      no    True
                 54     yes    True
                 56      no    True
                 58     yes    True
                 60      no   False
                 61     yes   False
unfurnished      7       no    True
                 9      yes    True
                 16      no    True
                 21      no    True
                 28      no    True
                 30      no    True
                 33     yes    True
                 38      no    True
                 42      no    True
                 48      no    True
                 50      no    True
                 51      no    True
                 55      no    True
                 67     yes   False
                 71     yes   False
                 72     yes   False
                 86      no   False
                 88     yes   False

### Replace all values in furnishingstatus with their uppercase equivalents.

In [134]:
df['furnishingstatus'].str.capitalize()

0           Furnished
1           Furnished
2      Semi-furnished
3           Furnished
4           Furnished
            ...
540       Unfurnished
541    Semi-furnished
542       Unfurnished
543         Furnished
544       Unfurnished
Name: furnishingstatus, Length: 545, dtype: object

In [135]:
df['furnishingstatus'].str.upper()

0           FURNISHED
1           FURNISHED
2      SEMI-FURNISHED
3           FURNISHED
4           FURNISHED
            ...
540       UNFURNISHED
541    SEMI-FURNISHED
542       UNFURNISHED
543         FURNISHED
544       UNFURNISHED
Name: furnishingstatus, Length: 545, dtype: object

In [136]:
df['furnishingstatus']=df['furnishingstatus'].replace({'furnished':'FURNISHED','semi-furnished':'SEMI-FURNISHED','unfurnished':'UNFURNISHED'})
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft,balcony,luxury
0,13300000,7420,4,2,3,True,False,False,False,True,2,True,FURNISHED,1792.452830,no,True
1,12250000,8960,4,4,4,True,False,False,False,True,3,False,FURNISHED,1367.187500,no,True
2,12250000,9960,3,2,2,True,False,True,False,False,2,True,SEMI-FURNISHED,1229.919679,yes,True
3,12215000,7500,4,2,2,True,False,True,False,True,3,True,FURNISHED,1628.666667,yes,True
4,11410000,7420,4,1,2,True,True,True,False,True,2,False,FURNISHED,1537.735849,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,True,False,True,False,False,2,False,UNFURNISHED,606.666667,yes,False
541,1767150,2400,3,1,1,False,False,False,False,False,0,False,SEMI-FURNISHED,736.312500,yes,False
542,1750000,3620,2,1,1,True,False,False,False,False,0,False,UNFURNISHED,483.425414,no,False
543,1750000,2910,3,1,1,False,False,False,False,False,0,False,FURNISHED,601.374570,no,False
544,1750000,3850,3,1,2,True,False,False,False,False,0,False,UNFURNISHED,454.545455,yes,False

### Use .pivot_table() with multiple aggregation functions (mean, max, std) for price grouped by stories and parking.

In [137]:
pd.pivot_table(df,
               values='price',
               index='stories',
               columns='parking',
               aggfunc=['mean','max','std']

               )

                 mean                                                   max  \
parking             0             1             2             3           0
stories
1        3.695366e+06  4.428356e+06  5.117571e+06  4.565167e+06   7420000.0
2        4.079344e+06  5.239105e+06  6.093000e+06  6.241667e+06  10150000.0
3        5.343722e+06  5.798917e+06  7.109667e+06           NaN   7560000.0
4        6.334500e+06  7.315000e+06  7.952585e+06  8.096667e+06   8463000.0

                                                     std                \
parking          1           2           3             0             1
stories
1        8645000.0  10850000.0   6300000.0  1.096730e+06  1.642325e+06
2        9310000.0  12250000.0  12215000.0  1.279300e+06  1.877771e+06
3        8043000.0  13300000.0         NaN  1.270940e+06  1.414739e+06
4        9800000.0  10150000.0  12250000.0  9.723566e+05  9.500636e+05


parking             2             3
stories
1        1.499432e+06  8.971959e+05
2        2.425736e+06  5.178857e+06
3        3.189072e+06           NaN
4        1.293146e+06  3.885683e+06