<a href="https://colab.research.google.com/github/PraveenChigurla/GrowTech-Tasks/blob/main/Task_3_pandas_task1_adult.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df=pd.read_csv('adult.csv')
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

### 1) Which education level has the largest representation in the dataset? Show counts in descending order.

In [3]:
df.groupby(['education'])['education'].count().sort_values(ascending=False)

education
HS-grad         15784
Some-college    10878
Bachelors        8025
Masters          2657
Assoc-voc        2061
11th             1812
Assoc-acdm       1601
10th             1389
7th-8th           955
Prof-school       834
9th               756
12th              657
Doctorate         594
5th-6th           509
1st-4th           247
Preschool          83
Name: education, dtype: int64

### 2) What are the top 3 occupations for people earning >50K?

In [4]:
df[df['income']=='>50K'].groupby('occupation')['occupation'].count().sort_values(ascending=False).head(3)

occupation
Exec-managerial    2908
Prof-specialty     2784
Sales              1475
Name: occupation, dtype: int64

### 3) Find the average hours-per-week worked by each marital-status.

In [5]:
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [6]:
df.groupby('marital-status')['hours-per-week'].mean().reset_index()

          marital-status  hours-per-week
0               Divorced       41.115483
1      Married-AF-spouse       39.810811
2     Married-civ-spouse       43.306984
3  Married-spouse-absent       39.684713
4          Never-married       36.891357
5              Separated       39.667974
6                Widowed       33.438076

### 4) Identify the top 5 native countries (excluding the US) of people earning >50K.

In [7]:
x=df[(df['income']=='>50K')& (df['native-country']!='United-States')]
x['native-country'].value_counts().head(5)

native-country
?              220
Philippines     85
Canada          63
India           62
Germany         58
Name: count, dtype: int64

In [8]:
x=df[(df['income']=='>50K')& (df['native-country']!='United-States')]
x.groupby('native-country')['native-country'].count().sort_values(ascending=False).head(5)          #'value_counts()' equivalent to 'count().sort_values(ascending=False)'

native-country
?              220
Philippines     85
Canada          63
India           62
Germany         58
Name: native-country, dtype: int64

### 5) Among people working 50+ hours/week, what proportion earn >50K?

In [9]:
x=df[df['hours-per-week']>50]
x

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
25,45,Self-emp-not-inc,432824,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,7298,0,90,United-States,>50K
27,23,Private,134446,HS-grad,9,Separated,Machine-op-inspct,Unmarried,Black,Male,0,0,54,United-States,<=50K
29,32,Self-emp-not-inc,109282,Some-college,10,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,60,United-States,<=50K
53,22,Private,54164,HS-grad,9,Never-married,Other-service,Not-in-family,White,Male,14084,0,60,United-States,>50K
54,38,Private,219446,9th,5,Married-spouse-absent,Exec-managerial,Not-in-family,White,Male,0,0,54,Mexico,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48811,35,?,320084,Bachelors,13,Married-civ-spouse,?,Wife,White,Female,0,0,55,United-States,>50K
48812,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
48813,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
48817,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
48829,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K

In [10]:
x['income'].value_counts()

income
<=50K    3212
>50K     2223
Name: count, dtype: int64

In [11]:
y=x['income'].value_counts(normalize=True)*100
y

income
<=50K    59.098436
>50K     40.901564
Name: proportion, dtype: float64

In [12]:
y['>50K']

np.float64(40.9015639374425)

In [13]:
(df[df['hours-per-week']>50]['income'].value_counts(normalize=True)*100)['>50K']

np.float64(40.9015639374425)

### 6) Find the age range of individuals with the highest capital-gain.

In [14]:
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [15]:
maxi=df['capital-gain'].max()
mini=df['capital-gain'].min()

min_age=df[df['capital-gain']==maxi]['age'].min()
max_age=df[df['capital-gain']==maxi]['age'].max()

print(f'age range={min_age}-{max_age}')

age range=21-80

### 7) For each education, show how many people work part-time (hours-per-week < 35).

In [16]:
df[df['hours-per-week']<35].groupby('education')['hours-per-week'].count()

education
10th             388
11th             690
12th             216
1st-4th           53
5th-6th           87
7th-8th          210
9th              150
Assoc-acdm       253
Assoc-voc        220
Bachelors        903
Doctorate         64
HS-grad         2302
Masters          273
Preschool         24
Prof-school       84
Some-college    2478
Name: hours-per-week, dtype: int64

### 8) What are the 5 most common combinations of workclass and occupation?

In [17]:
df[['workclass','occupation']].value_counts().head(5)

workclass  occupation
Private    Craft-repair       4748
           Sales              4439
           Adm-clerical       4208
           Other-service      4057
           Exec-managerial    3995
Name: count, dtype: int64

In [18]:
df.groupby(['workclass','occupation'])['occupation'].value_counts().sort_values(ascending=False).head(5)

workclass  occupation
Private    Craft-repair       4748
           Sales              4439
           Adm-clerical       4208
           Other-service      4057
           Exec-managerial    3995
Name: count, dtype: int64

### 9) Among women (gender == 'Female'), which education level is most frequent for >50K earners?

In [19]:
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [20]:
df[(df['income']=='>50K') & (df['gender']=='Female')]['education'].value_counts().head(1)

education
Bachelors    521
Name: count, dtype: int64

### 10) Find the average age of people with Doctorate education level.

In [21]:
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [22]:
df[df['education']=='Doctorate']['age'].mean()

np.float64(47.53030303030303)

### 11) Group by age_bucket (<=25, 26-35, 36-45, 46-55, 56-65, >65) and show the income distribution in each group.

In [23]:
import pandas as pd
age_bins = [-float('inf'), 25, 35, 45, 55, 65, float('inf')]
# age_labels = ['<=25', '26-35', '36-45', '46-55', '56-65', '>65']


df['xy']=pd.cut(df['age'],bins=age_bins)#, labels=age_labels)
df['xy']
df.groupby('xy')['income'].value_counts()

/tmp/ipykernel_1650/183802640.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('xy')['income'].value_counts()

xy            income
(-inf, 25.0]  <=50K      9458
              >50K        169
(25.0, 35.0]  <=50K     10340
              >50K       2379
(35.0, 45.0]  <=50K      7821
              >50K       4131
(45.0, 55.0]  <=50K      5041
              >50K       3255
(55.0, 65.0]  <=50K      3049
              >50K       1396
(65.0, inf]   <=50K      1446
              >50K        357
Name: count, dtype: int64

### 12) Find how many people work exactly 40 hours per week and their proportion of total.

In [24]:
len(df[df['hours-per-week']==40])/len(df)*100

46.68727734327013

In [25]:
(df['hours-per-week']==40).mean()*100

np.float64(46.68727734327013)

### 13) Show the top 3 education levels with the highest share of >50K earners.

In [26]:
df[df['income']=='>50K']['education'].value_counts().head(3)

education
Bachelors       3313
HS-grad         2503
Some-college    2063
Name: count, dtype: int64

### 14) For each race, calculate the most common occupation.

In [36]:
df.groupby('race')['occupation'].value_counts().groupby(level=0).head(1)

race                occupation
Amer-Indian-Eskimo  Craft-repair        61
Asian-Pac-Islander  Prof-specialty     289
Black               Other-service      824
Other               Craft-repair        58
White               Craft-repair      5504
Name: count, dtype: int64

### 15) Identify the top 5 most frequent marital-status + workclass pairs.

In [65]:
df.groupby(['marital-status','workclass'])['workclass'].count().sort_values(ascending=False).head()

marital-status      workclass
Married-civ-spouse  Private             14473
Never-married       Private             12243
Divorced            Private              4702
Married-civ-spouse  Self-emp-not-inc     2554
                    Local-gov            1536
Name: workclass, dtype: int64

In [51]:
df[['marital-status','workclass']].value_counts().head()

marital-status      workclass
Married-civ-spouse  Private             14473
Never-married       Private             12243
Divorced            Private              4702
Married-civ-spouse  Self-emp-not-inc     2554
                    Local-gov            1536
Name: count, dtype: int64

### 16) Find the average age of people grouped by gender and income.

In [46]:
df.groupby(['gender','income'])['age'].mean()

gender  income
Female  <=50K     36.278999
        >50K      42.219333
Male    <=50K     37.248548
        >50K      44.641863
Name: age, dtype: float64

### 17) Which occupation has the highest proportion of >50K earners?

In [77]:
(df[df['income']=='>50K']['occupation'].value_counts(normalize=True).sort_values(ascending=False)*100)

occupation
Exec-managerial      24.882348
Prof-specialty       23.821340
Sales                12.620861
Craft-repair         11.833661
Adm-clerical          6.571404
Transport-moving      4.115684
Tech-support          3.593737
Machine-op-inspct     3.183024
Protective-serv       2.635407
?                     2.267477
Other-service         1.745529
Farming-fishing       1.480277
Handlers-cleaners     1.180799
Armed-Forces          0.042783
Priv-house-serv       0.025670
Name: proportion, dtype: float64

In [76]:
(df[df['income']=='>50K']['occupation'].value_counts(normalize=True).sort_values(ascending=False)*100).nlargest(1)

occupation
Exec-managerial    24.882348
Name: proportion, dtype: float64

### 18) Identify the top 3 native countries where people work more than 60 hours per week.

In [81]:
df[df['hours-per-week']>60]['native-country'].value_counts().sort_values(ascending=False).nlargest(3)

native-country
United-States    1506
?                  33
Mexico             31
Name: count, dtype: int64

### 19) Find how many people have a capital-loss > 0 and group them by income.

In [101]:
len(df[df['capital-loss']>0])

2282

In [102]:
df[df['capital-loss']>0].groupby('income')['capital-loss'].count()

income
<=50K    1138
>50K     1144
Name: capital-loss, dtype: int64

### 20) Among people earning <=50K, find the most common education level.

In [108]:
df[df['income']=='<=50K']['education'].value_counts().head()

education
HS-grad         13281
Some-college     8815
Bachelors        4712
11th             1720
Assoc-voc        1539
Name: count, dtype: int64

### 21) Group people by hours-per-week ranges (<20, 20–39, 40, 41–59, >=60) and show the income distribution for each range.

In [124]:
hrs_range = [-float('inf'), 19, 39, 40, 59, float('inf')]
hrs_labels = ['<20', '20-39', '40', '41-59', '>=60']

df['hrs_grp'] = pd.cut(df['hours-per-week'], bins=hrs_range, labels=hrs_labels)
df
df.groupby(['hrs_grp'])['income'].value_counts()

/tmp/ipykernel_1650/1867618470.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['hrs_grp'])['income'].value_counts()

hrs_grp  income
<20      <=50K      2402
         >50K        189
20-39    <=50K      8190
         >50K        906
40       <=50K     17953
         >50K       4850
41-59    <=50K      6310
         >50K       4189
>=60     <=50K      2300
         >50K       1553
Name: count, dtype: int64

### 22) Which workclass group has the highest average capital-gain?

In [130]:
df.groupby('workclass')['capital-gain'].mean().sort_values(ascending=False)

workclass
Self-emp-inc        5132.794100
Self-emp-not-inc    1781.744692
Federal-gov          923.287709
Private              896.135374
Local-gov            798.228635
State-gov            756.336194
?                    502.946052
Without-pay          325.238095
Never-worked           0.000000
Name: capital-gain, dtype: float64

### 23) Find all individuals with Doctorate education working less than 20 hours per week.

In [139]:
df[df['education']=='Doctorate'][df['hours-per-week']<20]

/tmp/ipykernel_1650/1390096886.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['education']=='Doctorate'][df['hours-per-week']<20]

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,xy,hrs_grp
166,58,Self-emp-not-inc,159021,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,16,United-States,>50K,"(55.0, 65.0]",<20
3733,77,State-gov,267799,Doctorate,16,Married-spouse-absent,Prof-specialty,Not-in-family,White,Male,0,0,4,United-States,>50K,"(65.0, inf]",<20
9693,48,Local-gov,452402,Doctorate,16,Never-married,Prof-specialty,Unmarried,Black,Female,0,0,15,United-States,<=50K,"(45.0, 55.0]",<20
11517,70,?,116080,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,2,United-States,>50K,"(65.0, inf]",<20
13920,73,Self-emp-not-inc,110787,Doctorate,16,Married-civ-spouse,Exec-managerial,Husband,White,Male,1409,0,2,United-States,<=50K,"(65.0, inf]",<20
16470,58,State-gov,109567,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,1,United-States,>50K,"(55.0, 65.0]",<20
18399,61,?,188172,Doctorate,16,Widowed,?,Not-in-family,White,Female,0,0,5,United-States,<=50K,"(55.0, 65.0]",<20
20299,72,?,118902,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,2392,6,United-States,>50K,"(65.0, inf]",<20
20517,75,Self-emp-not-inc,231741,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,4931,0,3,United-States,<=50K,"(65.0, inf]",<20
26465,42,Self-emp-not-inc,115323,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,7,?,<=50K,"(35.0, 45.0]",<20
27491,36,Self-emp-not-inc,188972,Doctorate,16,Separated,Prof-specialty,Unmarried,White,Female,0,0,10,Canada,<=50K,"(35.0, 45.0]",<20
30611,67,?,129188,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,20051,0,5,United-States,>50K,"(65.0, inf]",<20
32854,30,Private,174215,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,15,United-States,<=50K,"(25.0, 35.0]",<20
35452,28,Private,115945,Doctorate,16,Never-married,Adm-clerical,Own-child,White,Male,0,0,18,United-States,<=50K,"(25.0, 35.0]",<20
36961,58,Private,186385,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,8,United-States,<=50K,"(55.0, 65.0]",<20
41830,67,State-gov,239705,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Black,Male,0,0,12,?,<=50K,"(65.0, inf]",<20
42257,63,?,133166,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,12,United-States,<=50K,"(55.0, 65.0]",<20
44457,79,Federal-gov,62176,Doctorate,16,Widowed,Exec-managerial,Not-in-family,White,Male,0,0,6,United-States,>50K,"(65.0, inf]",<20
48820,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K,"(65.0, inf]",<20

### 24) Find the percentage of females in each workclass.

In [186]:
df.groupby('workclass')['gender'].value_counts(normalize=True).mul(100).unstack()

gender               Female       Male
workclass
?                 45.373348  54.626652
Federal-gov       31.564246  68.435754
Local-gov         40.114796  59.885204
Never-worked      30.000000  70.000000
Private           34.209284  65.790716
Self-emp-inc      12.448378  87.551622
Self-emp-not-inc  16.286898  83.713102
State-gov         38.515901  61.484099
Without-pay       33.333333  66.666667

In [193]:
# Calculate the percentage of each gender within each workclass
gender_percentages = df.groupby('workclass')['gender'].value_counts(normalize=True).mul(100).unstack()

# Select and display only the female percentages
display(gender_percentages['Female'])

workclass
?                   45.373348
Federal-gov         31.564246
Local-gov           40.114796
Never-worked        30.000000
Private             34.209284
Self-emp-inc        12.448378
Self-emp-not-inc    16.286898
State-gov           38.515901
Without-pay         33.333333
Name: Female, dtype: float64

In [185]:
((df.groupby(['workclass'])['gender']).value_counts(normalize=True).mul(100)).groupby(level=0).tail(1)

workclass         gender
?                 Female    45.373348
Federal-gov       Female    31.564246
Local-gov         Female    40.114796
Never-worked      Female    30.000000
Private           Female    34.209284
Self-emp-inc      Female    12.448378
Self-emp-not-inc  Female    16.286898
State-gov         Female    38.515901
Without-pay       Female    33.333333
Name: proportion, dtype: float64

### 25) Identify the oldest person in the dataset and display all their details.

In [194]:
df[df['age']==df['age'].max()]

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,xy,hrs_grp
899,90,Private,149069,Assoc-acdm,12,Married-civ-spouse,Sales,Husband,White,Male,0,1825,50,United-States,>50K,"(65.0, inf]",41-59
3496,90,Self-emp-not-inc,83601,Prof-school,15,Widowed,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K,"(65.0, inf]",>=60
6976,90,Private,250832,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,2414,0,40,United-States,<=50K,"(65.0, inf]",40
7414,90,Private,227796,Assoc-acdm,12,Never-married,Exec-managerial,Not-in-family,White,Male,6097,0,45,United-States,>50K,"(65.0, inf]",41-59
7419,90,Self-emp-not-inc,122348,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,20051,0,45,United-States,>50K,"(65.0, inf]",41-59
8427,90,Federal-gov,311184,Masters,14,Divorced,Prof-specialty,Not-in-family,White,Male,0,0,99,United-States,<=50K,"(65.0, inf]",>=60
8982,90,Private,225063,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,South,<=50K,"(65.0, inf]",40
10735,90,Local-gov,188242,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,11678,0,40,United-States,>50K,"(65.0, inf]",40
11871,90,?,50746,10th,6,Divorced,?,Not-in-family,White,Female,0,0,7,United-States,<=50K,"(65.0, inf]",<20
12446,90,Private,347074,Some-college,10,Never-married,Adm-clerical,Own-child,White,Female,0,1944,12,United-States,<=50K,"(65.0, inf]",<20
13958,90,Private,272752,Some-college,10,Never-married,Other-service,Own-child,White,Male,0,0,10,United-States,<=50K,"(65.0, inf]",<20
15088,90,Private,197613,HS-grad,9,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,>50K,"(65.0, inf]",40
16503,90,Private,51744,HS-grad,9,Never-married,Other-service,Not-in-family,Black,Male,0,2206,40,United-States,<=50K,"(65.0, inf]",40
17321,90,Private,137018,HS-grad,9,Never-married,Other-service,Not-in-family,White,Female,0,0,40,United-States,<=50K,"(65.0, inf]",40
18216,90,Private,221832,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,<=50K,"(65.0, inf]",41-59
18584,90,Private,52386,Some-college,10,Never-married,Other-service,Not-in-family,Asian-Pac-Islander,Male,0,0,35,United-States,<=50K,"(65.0, inf]",20-39
19172,90,Private,171956,Some-college,10,Separated,Adm-clerical,Own-child,White,Female,0,0,40,Puerto-Rico,<=50K,"(65.0, inf]",40
20351,90,Private,313986,11th,7,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,40,United-States,<=50K,"(65.0, inf]",40
20390,90,?,256514,Bachelors,13,Widowed,?,Other-relative,White,Female,991,0,10,United-States,<=50K,"(65.0, inf]",<20
21385,90,Private,52386,Some-college,10,Never-married,Other-service,Not-in-family,Asian-Pac-Islander,Male,0,0,35,United-States,<=50K,"(65.0, inf]",20-39
21553,90,Private,141758,9th,5,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,<=50K,"(65.0, inf]",40
21651,90,Local-gov,227796,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,20051,0,60,United-States,>50K,"(65.0, inf]",>=60
21687,90,Private,51744,Masters,14,Never-married,Exec-managerial,Not-in-family,Black,Male,0,0,50,United-States,>50K,"(65.0, inf]",41-59
22513,90,Self-emp-not-inc,155981,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,10566,0,50,United-States,<=50K,"(65.0, inf]",41-59
22905,90,Private,313986,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K,"(65.0, inf]",40
25087,90,Private,87372,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,20051,0,72,United-States,>50K,"(65.0, inf]",>=60
25244,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K,"(65.0, inf]",40
25254,90,Private,46786,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,9386,0,15,United-States,>50K,"(65.0, inf]",<20
26491,90,Self-emp-not-inc,282095,Some-college,10,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,40,United-States,<=50K,"(65.0, inf]",40
26826,90,Private,175491,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,9386,0,50,Ecuador,>50K,"(65.0, inf]",41-59
27793,90,Private,87285,HS-grad,9,Never-married,Other-service,Own-child,White,Female,0,0,24,United-States,<=50K,"(65.0, inf]",20-39
28012,90,?,39824,HS-grad,9,Widowed,?,Not-in-family,White,Male,401,0,4,United-States,<=50K,"(65.0, inf]",<20
28277,90,Private,40388,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Male,0,0,55,United-States,<=50K,"(65.0, inf]",41-59
28732,90,?,225063,Some-college,10,Never-married,?,Own-child,Asian-Pac-Islander,Male,0,0,10,South,<=50K,"(65.0, inf]",<20
29256,90,Private,250832,10th,6,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,<=50K,"(65.0, inf]",40
30440,90,Local-gov,187749,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Husband,Asian-Pac-Islander,Male,0,0,20,Philippines,<=50K,"(65.0, inf]",20-39
31637,90,Private,90523,HS-grad,9,Widowed,Transport-moving,Unmarried,White,Male,0,0,99,United-States,<=50K,"(65.0, inf]",>=60
32173,90,Private,88991,Bachelors,13,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,England,>50K,"(65.0, inf]",40
34558,90,Private,311184,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,20,?,<=50K,"(65.0, inf]",20-39
34694,90,Private,313749,Bachelors,13,Never-married,Prof-specialty,Own-child,White,Female,0,0,10,United-States,<=50K,"(65.0, inf]",<20
35006,90,Local-gov,153602,HS-grad,9,Married-civ-spouse,Other-service,Husband,White,Male,6767,0,40,United-States,<=50K,"(65.0, inf]",40
35113,90,Private,115306,Masters,14,Never-married,Exec-managerial,Own-child,White,Female,0,0,40,United-States,<=50K,"(65.0, inf]",40
35493,90,Private,139660,Some-college,10,Divorced,Sales,Unmarried,Black,Female,0,0,37,United-States,<=50K,"(65.0, inf]",20-39
35770,90,Private,84553,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,<=50K,"(65.0, inf]",40
36028,90,Private,226968,7th-8th,4,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,<=50K,"(65.0, inf]",40
36891,90,Private,206667,Masters,14,Married-civ-spouse,Prof-specialty,Wife,White,Female,0,0,40,United-States,>50K,"(65.0, inf]",40
38501,90,Private,52386,Bachelors,13,Never-married,Prof-specialty,Not-in-family,Asian-Pac-Islander,Male,0,0,40,United-States,<=50K,"(65.0, inf]",40
40324,90,Self-emp-not-inc,82628,HS-grad,9,Never-married,Exec-managerial,Not-in-family,White,Male,2964,0,12,United-States,<=50K,"(65.0, inf]",<20
40519,90,?,166343,1st-4th,2,Widowed,?,Not-in-family,Black,Female,0,0,40,United-States,<=50K,"(65.0, inf]",40
41584,90,?,175444,7th-8th,4,Separated,?,Not-in-family,White,Female,0,0,15,United-States,<=50K,"(65.0, inf]",<20
44744,90,Federal-gov,195433,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,30,United-States,<=50K,"(65.0, inf]",20-39
47311,90,Private,47929,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,<=50K,"(65.0, inf]",40
47977,90,?,313986,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,>50K,"(65.0, inf]",40
48558,90,Private,313749,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,25,United-States,<=50K,"(65.0, inf]",20-39
48648,90,Local-gov,214594,7th-8th,4,Married-civ-spouse,Protective-serv,Husband,White,Male,2653,0,40,United-States,<=50K,"(65.0, inf]",40

In [199]:
# Grabs the row(s) with the maximum age value
df.nlargest(1, 'age', keep='all')

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,xy,hrs_grp
899,90,Private,149069,Assoc-acdm,12,Married-civ-spouse,Sales,Husband,White,Male,0,1825,50,United-States,>50K,"(65.0, inf]",41-59
3496,90,Self-emp-not-inc,83601,Prof-school,15,Widowed,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K,"(65.0, inf]",>=60
6976,90,Private,250832,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,2414,0,40,United-States,<=50K,"(65.0, inf]",40
7414,90,Private,227796,Assoc-acdm,12,Never-married,Exec-managerial,Not-in-family,White,Male,6097,0,45,United-States,>50K,"(65.0, inf]",41-59
7419,90,Self-emp-not-inc,122348,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,20051,0,45,United-States,>50K,"(65.0, inf]",41-59
8427,90,Federal-gov,311184,Masters,14,Divorced,Prof-specialty,Not-in-family,White,Male,0,0,99,United-States,<=50K,"(65.0, inf]",>=60
8982,90,Private,225063,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,South,<=50K,"(65.0, inf]",40
10735,90,Local-gov,188242,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,11678,0,40,United-States,>50K,"(65.0, inf]",40
11871,90,?,50746,10th,6,Divorced,?,Not-in-family,White,Female,0,0,7,United-States,<=50K,"(65.0, inf]",<20
12446,90,Private,347074,Some-college,10,Never-married,Adm-clerical,Own-child,White,Female,0,1944,12,United-States,<=50K,"(65.0, inf]",<20
13958,90,Private,272752,Some-college,10,Never-married,Other-service,Own-child,White,Male,0,0,10,United-States,<=50K,"(65.0, inf]",<20
15088,90,Private,197613,HS-grad,9,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,>50K,"(65.0, inf]",40
16503,90,Private,51744,HS-grad,9,Never-married,Other-service,Not-in-family,Black,Male,0,2206,40,United-States,<=50K,"(65.0, inf]",40
17321,90,Private,137018,HS-grad,9,Never-married,Other-service,Not-in-family,White,Female,0,0,40,United-States,<=50K,"(65.0, inf]",40
18216,90,Private,221832,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,<=50K,"(65.0, inf]",41-59
18584,90,Private,52386,Some-college,10,Never-married,Other-service,Not-in-family,Asian-Pac-Islander,Male,0,0,35,United-States,<=50K,"(65.0, inf]",20-39
19172,90,Private,171956,Some-college,10,Separated,Adm-clerical,Own-child,White,Female,0,0,40,Puerto-Rico,<=50K,"(65.0, inf]",40
20351,90,Private,313986,11th,7,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,40,United-States,<=50K,"(65.0, inf]",40
20390,90,?,256514,Bachelors,13,Widowed,?,Other-relative,White,Female,991,0,10,United-States,<=50K,"(65.0, inf]",<20
21385,90,Private,52386,Some-college,10,Never-married,Other-service,Not-in-family,Asian-Pac-Islander,Male,0,0,35,United-States,<=50K,"(65.0, inf]",20-39
21553,90,Private,141758,9th,5,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,<=50K,"(65.0, inf]",40
21651,90,Local-gov,227796,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,20051,0,60,United-States,>50K,"(65.0, inf]",>=60
21687,90,Private,51744,Masters,14,Never-married,Exec-managerial,Not-in-family,Black,Male,0,0,50,United-States,>50K,"(65.0, inf]",41-59
22513,90,Self-emp-not-inc,155981,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,10566,0,50,United-States,<=50K,"(65.0, inf]",41-59
22905,90,Private,313986,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K,"(65.0, inf]",40
25087,90,Private,87372,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,20051,0,72,United-States,>50K,"(65.0, inf]",>=60
25244,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K,"(65.0, inf]",40
25254,90,Private,46786,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,9386,0,15,United-States,>50K,"(65.0, inf]",<20
26491,90,Self-emp-not-inc,282095,Some-college,10,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,40,United-States,<=50K,"(65.0, inf]",40
26826,90,Private,175491,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,9386,0,50,Ecuador,>50K,"(65.0, inf]",41-59
27793,90,Private,87285,HS-grad,9,Never-married,Other-service,Own-child,White,Female,0,0,24,United-States,<=50K,"(65.0, inf]",20-39
28012,90,?,39824,HS-grad,9,Widowed,?,Not-in-family,White,Male,401,0,4,United-States,<=50K,"(65.0, inf]",<20
28277,90,Private,40388,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Male,0,0,55,United-States,<=50K,"(65.0, inf]",41-59
28732,90,?,225063,Some-college,10,Never-married,?,Own-child,Asian-Pac-Islander,Male,0,0,10,South,<=50K,"(65.0, inf]",<20
29256,90,Private,250832,10th,6,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,<=50K,"(65.0, inf]",40
30440,90,Local-gov,187749,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Husband,Asian-Pac-Islander,Male,0,0,20,Philippines,<=50K,"(65.0, inf]",20-39
31637,90,Private,90523,HS-grad,9,Widowed,Transport-moving,Unmarried,White,Male,0,0,99,United-States,<=50K,"(65.0, inf]",>=60
32173,90,Private,88991,Bachelors,13,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,England,>50K,"(65.0, inf]",40
34558,90,Private,311184,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,20,?,<=50K,"(65.0, inf]",20-39
34694,90,Private,313749,Bachelors,13,Never-married,Prof-specialty,Own-child,White,Female,0,0,10,United-States,<=50K,"(65.0, inf]",<20
35006,90,Local-gov,153602,HS-grad,9,Married-civ-spouse,Other-service,Husband,White,Male,6767,0,40,United-States,<=50K,"(65.0, inf]",40
35113,90,Private,115306,Masters,14,Never-married,Exec-managerial,Own-child,White,Female,0,0,40,United-States,<=50K,"(65.0, inf]",40
35493,90,Private,139660,Some-college,10,Divorced,Sales,Unmarried,Black,Female,0,0,37,United-States,<=50K,"(65.0, inf]",20-39
35770,90,Private,84553,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,<=50K,"(65.0, inf]",40
36028,90,Private,226968,7th-8th,4,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,<=50K,"(65.0, inf]",40
36891,90,Private,206667,Masters,14,Married-civ-spouse,Prof-specialty,Wife,White,Female,0,0,40,United-States,>50K,"(65.0, inf]",40
38501,90,Private,52386,Bachelors,13,Never-married,Prof-specialty,Not-in-family,Asian-Pac-Islander,Male,0,0,40,United-States,<=50K,"(65.0, inf]",40
40324,90,Self-emp-not-inc,82628,HS-grad,9,Never-married,Exec-managerial,Not-in-family,White,Male,2964,0,12,United-States,<=50K,"(65.0, inf]",<20
40519,90,?,166343,1st-4th,2,Widowed,?,Not-in-family,Black,Female,0,0,40,United-States,<=50K,"(65.0, inf]",40
41584,90,?,175444,7th-8th,4,Separated,?,Not-in-family,White,Female,0,0,15,United-States,<=50K,"(65.0, inf]",<20
44744,90,Federal-gov,195433,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,30,United-States,<=50K,"(65.0, inf]",20-39
47311,90,Private,47929,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,<=50K,"(65.0, inf]",40
47977,90,?,313986,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,>50K,"(65.0, inf]",40
48558,90,Private,313749,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,25,United-States,<=50K,"(65.0, inf]",20-39
48648,90,Local-gov,214594,7th-8th,4,Married-civ-spouse,Protective-serv,Husband,White,Male,2653,0,40,United-States,<=50K,"(65.0, inf]",40

In [197]:
# Returns a single Series representing the first person with the maximum age
df.loc[df['age'].idxmax()]

age                                90
workclass                     Private
fnlwgt                         149069
education                  Assoc-acdm
educational-num                    12
marital-status     Married-civ-spouse
occupation                      Sales
relationship                  Husband
race                            White
gender                           Male
capital-gain                        0
capital-loss                     1825
hours-per-week                     50
native-country          United-States
income                           >50K
xy                        (65.0, inf]
hrs_grp                         41-59
Name: 899, dtype: object

### 26) Among all races, who works the least average hours per week?

In [218]:
df.groupby('race')['hours-per-week'].mean().sort_values()

race
Black                 38.597866
Other                 39.201970
Asian-Pac-Islander    39.884793
Amer-Indian-Eskimo    40.272340
White                 40.660170
Name: hours-per-week, dtype: float64

In [216]:
(df.groupby('race')['hours-per-week'].mean().sort_values()).nsmallest(2)

race
Black    38.597866
Other    39.201970
Name: hours-per-week, dtype: float64

### 27) Which marital-status group has the highest proportion of >50K earners?

In [235]:
df.groupby('marital-status')['income'].value_counts(normalize=True).mul(100).unstack().sort_values(by='>50K',ascending=False)

income                     <=50K       >50K
marital-status
Married-civ-spouse     55.386747  44.613253
Married-AF-spouse      62.162162  37.837838
Divorced               89.883914  10.116086
Married-spouse-absent  90.764331   9.235669
Widowed                91.567852   8.432148
Separated              93.529412   6.470588
Never-married          95.452007   4.547993

### 28) Find the most frequent combination of education and income.

In [243]:
df.groupby('education')['income'].value_counts().sort_values(ascending=False).head(1)

education  income
HS-grad    <=50K     13281
Name: count, dtype: int64

### 29) Group people by occupation and calculate how many have capital-gain > 0.

In [247]:
df[df['capital-gain']>0].groupby('occupation').size()

occupation
?                    174
Adm-clerical         343
Armed-Forces           1
Craft-repair         478
Exec-managerial      810
Farming-fishing      103
Handlers-cleaners     91
Machine-op-inspct    190
Other-service        174
Priv-house-serv       10
Prof-specialty       832
Protective-serv       73
Sales                470
Tech-support         129
Transport-moving     157
dtype: int64

### 30) Find the top 5 age values where people earn >50K.

In [251]:
df[df['income']=='>50K']['age'].max()

90

In [250]:
df[df['income']=='>50K']['age'].value_counts().sort_values(ascending=False).head()

age
46    439
47    429
41    427
39    423
37    422
Name: count, dtype: int64

In [30]:
df[df['income']=='>50K'].groupby('age')['age'].size().sort_values(ascending=False).head() #size() creating single index

age
46    439
47    429
41    427
39    423
37    422
Name: age, dtype: int64

In [248]:
df[df['income']=='>50K'].groupby('age')['age'].value_counts().sort_values(ascending=False).head()  #value_counts() creating multiindex

age
46    439
47    429
41    427
39    423
37    422
Name: count, dtype: int64